/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Isla.glb --types 
*/

import * as THREE from 'three'
type GLTFAction = THREE.AnimationClip;
import { useGLTF } from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber';
import type { GLTF } from 'three/examples/jsm/loaders/GLTFLoader.js'

type GLTFResult = GLTF & {
  nodes: {
    Acue: THREE.Mesh
    Text: THREE.Mesh
    Cartel: THREE.Mesh
    Isla: THREE.Mesh
    Agua: THREE.Mesh
    Roca_1: THREE.Mesh
    Roca_2: THREE.Mesh
    Roca_3: THREE.Mesh
    Arbol: THREE.Mesh
    Arbol001: THREE.Mesh
    Arbol002: THREE.Mesh
    Arbol003: THREE.Mesh
    Roca_1001: THREE.Mesh
    Arbol004: THREE.Mesh
    Arbol005: THREE.Mesh
    Arbol006: THREE.Mesh
    Roca_3001: THREE.Mesh
    Arbol007: THREE.Mesh
    Arbol008: THREE.Mesh
  }
  materials: {
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Modelo(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/Isla.glb')  as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Acue.geometry} material={materials['Material.003']} position={[4.82, 2.357, -8.151]} rotation={[-Math.PI, 1.568, -Math.PI]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Material.006']} position={[1.701, 1.768, 6.345]} rotation={[Math.PI / 2, 0, 1.589]} scale={0.472} />
      <mesh geometry={nodes.Cartel.geometry} material={materials['Material.007']} position={[1.906, 0.357, 7.116]} rotation={[0, 1.571, 0]} scale={[0.124, 0.473, 0.111]} />
      <mesh geometry={nodes.Isla.geometry} material={materials.Material} position={[4.435, 0, -0.281]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Agua.geometry} material={materials.Material} position={[-5.424, 0.283, -0.278]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Roca_1.geometry} material={materials.Material} position={[-4.697, 0.633, 1.386]} rotation={[-Math.PI, 0, -Math.PI]} />
      <mesh geometry={nodes.Roca_2.geometry} material={materials.Material} position={[-4.691, 0.616, -1.776]} rotation={[2.996, -0.109, 3.082]} scale={1.48} />
      <mesh geometry={nodes.Roca_3.geometry} material={materials.Material} position={[-4.097, 0.552, 0.007]} rotation={[0.197, -0.744, 0.091]} scale={1.714} />
      <mesh geometry={nodes.Arbol.geometry} material={materials.Material} position={[-1.511, 2.936, 3.416]} rotation={[3.06, 0.188, -3.126]} scale={[0.778, 0.426, 0.778]} />
      <mesh geometry={nodes.Arbol001.geometry} material={materials['Material.002']} position={[8.813, 2.382, -8.64]} rotation={[0.2, -1.156, 0.184]} scale={[0.612, 0.335, 0.612]} />
      <mesh geometry={nodes.Arbol002.geometry} material={materials.Material} position={[10.186, 2.993, 1.682]} rotation={[3.06, 0.188, -3.126]} scale={[0.778, 0.426, 0.778]} />
      <mesh geometry={nodes.Arbol003.geometry} material={materials['Material.002']} position={[-1.388, 1.707, 5.118]} rotation={[0.2, -1.156, 0.184]} scale={[0.442, 0.242, 0.442]} />
      <mesh geometry={nodes.Roca_1001.geometry} material={materials.Material} position={[-2.918, 0.165, 4.591]} rotation={[-Math.PI, 0, -Math.PI]} scale={[-0.952, -0.575, -0.952]} />
      <mesh geometry={nodes.Arbol004.geometry} material={materials['Material.002']} position={[-2.909, 1.707, -4.216]} rotation={[0.2, -1.156, 0.184]} scale={[0.442, 0.242, 0.442]} />
      <mesh geometry={nodes.Arbol005.geometry} material={materials['Material.002']} position={[6.814, 1.669, -7.321]} rotation={[0.2, -1.156, 0.184]} scale={[0.442, 0.242, 0.442]} />
      <mesh geometry={nodes.Arbol006.geometry} material={materials['Material.002']} position={[11.042, 1.622, 3.712]} rotation={[0.2, -1.156, 0.184]} scale={[0.442, 0.242, 0.442]} />
      <mesh geometry={nodes.Roca_3001.geometry} material={materials.Material} position={[9.839, -0.111, 3.304]} rotation={[-2.944, 0.744, 3.051]} scale={[-1.636, -1.233, -1.683]} />
      <mesh geometry={nodes.Arbol007.geometry} material={materials['Material.002']} position={[9.298, 1.62, -2.79]} rotation={[0.2, -1.156, 0.184]} scale={[0.442, 0.242, 0.442]} />
      <mesh geometry={nodes.Arbol008.geometry} material={materials['Material.002']} position={[0.916, 1.633, -5.891]} rotation={[0.2, -1.156, 0.184]} scale={[0.442, 0.242, 0.442]} />
    </group>
  )
}

useGLTF.preload('/Isla.glb')
